// export { default as AccentGrid } from './AccentGrid';
// export { default as AmberVisual } from './AmberVisual';
// export { default as AzurePro } from './AzurePro';
// export { default as BlockBranding } from './BlockBranding';
// export { default as BlueFrame } from './BlueFrame';
// export { default as BorderedElegant } from './BorderedElegant';
// export { default as BrickFormal } from './BrickFormal';
// export { default as BubbleHeader } from './BubbleHeader';
// export { default as CenteredInitials } from './CenteredInitials';
// export { default as Classic } from './Classic';
// export { default as CloudSoft } from './CloudSoft';
// export { default as Creative } from './Creative';
// export { default as CrimsonEdge } from './CrimsonEdge';
// export { default as CyanGrid } from './CyanGrid';
// export { default as Executive } from './Executive';
// export { default as ForestSidebar } from './ForestSidebar';
// export { default as Formal } from './Formal';
// export { default as ImpactHeader } from './ImpactHeader';
// export { default as IndigoElite } from './IndigoElite';
// export { default as MarineClean } from './MarineClean';
// export { default as MarineCompact } from './MarineCompact';
// export { default as Minimal } from './Minimal';
// export { default as MintFresh } from './MintFresh';
// export { default as MochaCreative } from './MochaCreative';
// export { default as Modern } from './Modern';
// export { default as ModernCircle } from './ModernCircle';
// export { default as ModernGold } from './ModernGold';
// export { default as NavySidebar } from './NavySidebar';
// export { default as NightAdmin } from './NightAdmin';
// export { default as OceanATS } from './OceanATS';
// export { default as OrangePunch } from './OrangePunch';
// export { default as PointerBanner } from './PointerBanner';
// export { default as Professional } from './Professional';
// export { default as ProfessionalColumns } from './ProfessionalColumns';
// export { default as RubyCreative } from './RubyCreative';
// export { default as RuleMinimalist } from './RuleMinimalist';
// export { default as SandMinimal } from './SandMinimal';
// export { default as Skyline } from './Skyline';
// export { default as SlateDuo } from './SlateDuo';
// export { default as SoftSerif } from './SoftSerif';
// export { default as SunsetSlim } from './SunsetSlim';
// export { default as TealInnovator } from './TealInnovator';
// export { default as Tech } from './Tech';


// --- STANDARD TEMPLATES ---

export { default as AccentGrid } from './AccentGrid';
export { default as Mosaic } from './Mosaic';
export { default as Artistic } from './Artistic';
export { default as Infographic } from './Infographic';
export { default as AmberVisual } from './AmberVisual';
export { default as AzurePro } from './AzurePro';
export { default as BlockBranding } from './BlockBranding';
export { default as BlueFrame } from './BlueFrame';
export { default as BorderedElegant } from './BorderedElegant';
export { default as BrickFormal } from './BrickFormal';
export { default as BubbleHeader } from './BubbleHeader';
export { default as CenteredInitials } from './CenteredInitials';
export { default as Classic } from './Classic';
export { default as CloudSoft } from './CloudSoft';
export { default as Creative } from './Creative';
export { default as CrimsonEdge } from './CrimsonEdge';
export { default as CyanGrid } from './CyanGrid';
export { default as Executive } from './Executive';
export { default as ForestSidebar } from './ForestSidebar';
export { default as Formal } from './Formal';
export { default as ImpactHeader } from './ImpactHeader';
export { default as IndigoElite } from './IndigoElite';
export { default as MarineClean } from './MarineClean';
export { default as MarineCompact } from './MarineCompact';
export { default as Minimal } from './Minimal';
export { default as MintFresh } from './MintFresh';
export { default as MochaCreative } from './MochaCreative';
export { default as Modern } from './Modern';
export { default as ModernCircle } from './ModernCircle';
export { default as ModernGold } from './ModernGold';
export { default as NavySidebar } from './NavySidebar';
export { default as NightAdmin } from './NightAdmin';
export { default as OceanATS } from './OceanATS';
export { default as OrangePunch } from './OrangePunch';
export { default as PointerBanner } from './PointerBanner';
export { default as Professional } from './Professional';
export { default as ProfessionalColumns } from './ProfessionalColumns';
export { default as RubyCreative } from './RubyCreative';
export { default as RuleMinimalist } from './RuleMinimalist';
export { default as SandMinimal } from './SandMinimal';
export { default as Skyline } from './Skyline';
export { default as SlateDuo } from './SlateDuo';
export { default as SoftSerif } from './SoftSerif';
export { default as SunsetSlim } from './SunsetSlim';
export { default as TealInnovator } from './TealInnovator';
export { default as Tech } from './Tech';
export { default as Academic } from './Academic';
export { default as Ats } from './Ats';
export { default as Berlin } from './Berlin';
export { default as Card } from './Card';
export { default as Japanese } from './Japanese';
export { default as Luxe } from './Luxe';


// --- NEW ROLE-BASED TEMPLATES ---
export { default as Accounting } from './Accounting';
export { default as Architect } from './Architect';
export { default as BusinessAnalyst } from './BusinessAnalyst';
export { default as Coder } from './Coder';
export { default as Creative2 } from './Creative2';
export { default as DataScientist } from './DataScientist';
export { default as Startup } from './Startup';
export { default as Designer } from './Designer';
export { default as Developer } from './Developer';
export { default as Engineer } from './Engineer';
export { default as Marketing } from './Marketing';
export { default as Medical } from './Medical';
export { default as Metro } from './Metro';
export { default as ProductManager } from './ProductManager';
export { default as Sales } from './Sales';
export { default as SoftwareEngineer } from './SoftwareEngineer';
export { default as Teacher } from './Teacher';
export { default as InfoBlue } from './InfoBlue';
export { default as InfoExecutive } from './InfoExecutive';
export { default as InfoTeal } from './InfoTeal';
export { default as InfoGreen } from './InfoGreen';
export { default as InfoNavy } from './InfoNavy';